docker-pull: docker-pull-vc docker-pull-pkcs11

docker-pull-vc:
	docker pull docker.sunet.se/dc4eu/issuer:<%= @vc_version %>
	docker pull docker.sunet.se/dc4eu/datastore:<%= @vc_version %>
	docker pull docker.sunet.se/dc4eu/registry:<%= @vc_version %>
	docker pull docker.sunet.se/dc4eu/verifier:<%= @vc_version %>

docker-pull-pkcs11:
	docker pull docker.sunet.se/dc4eu/<%= @pdfsigner_flavor %>:<%= @pdfsigner_version %>

dev-release: docker-pull
	systemctl restart sunet-vc.service