# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  ldap:
    image: <%= @ds_image %>:<%= @ds_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/ds_389/data:/data
    environment:
      DS_SUFFIX_NAME: <%= @dir_suffix %>
      DS_DM_PASSWORD: "<%= @dir_manager_password %>"
    ports:
      - 3389:3389
      - 3636:3636
    restart: always

