# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  ldap:
    image: <%= @ds_image %>:<%= @ds_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/ds_389/data:/data
    environment:
      DIR_SUFFIX: <%= @dir_suffix %>
      DIR_ADMIN_USERNAME: "<%= @dir_admin_username %>"
      DIR_MANAGER_PASSWORD: "<%= @dir_manager_password %>"
      DIR_ADMIN_UID: "15000"
      DIR_USERS_HOME: "/users"
    ports:
      - 3389:3389
      - 3636:3636
    restart: always

