# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  ldap:
    image: <%= @ds_image %>:<%= @ds_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/ds_389/data:/var/lib/dirsrv:Z
      - /opt/ds_389/config:/etc/dirsrv:Z
      - /opt/ds_389/logs:/var/log/dirsrv:Z
      - /opt/ds_389/certs:/certs:Z
    environment:
      DIR_SUFFIX: <%= @dir_suffix %>
      DIR_ADMIN_USERNAME: "<%= @dir_admin_username %>"
      DIR_MANAGER_PASSWORD: "<%= @dir_manager_password %>"
      DIR_ADMIN_UID: "15000"
      DIR_USERS_HOME: "/users"
    ports:
      - 389:389
      - 636:636
    restart: always

