#!/usr/bin/env bash
set -euo pipefail

# === Configuration ===
CERT_DIR="/opt/redis/cert"
CERT_DST="${CERT_DIR}/cert.pem"
KEY_DST="${CERT_DIR}/privkey.pem"
fqdn=$(hostname -f)
password=$(eyaml decrypt -f /etc/hiera/data/local.eyaml --pkcs7-private-key=/etc/hiera/eyaml/private_key.pkcs7.pem --pkcs7-public-key=/etc/hiera/eyaml/public_certkey.pkcs7.pem | awk '/^redis_password: /{print $2}')

# Valkey runtime UID/GID (inside container)
REDIS_UID=999
REDIS_GID=999

# === Sanity checks ===
if [ -z "${RENEWED_LINEAGE:-}" ]; then
	echo "ERROR: RENEWED_LINEAGE not set (not running from certbot?)" >&2
	exit 1
fi


# === Ensure directory exists ===
install -d -m 755 "${CERT_DIR}"

# === Install public certificate ===
install -m 0644 \
	"${RENEWED_LINEAGE}/cert.pem" \
	"${CERT_DST}"

# === Install private key securely ===
install -m 0600 \
	"${RENEWED_LINEAGE}/privkey.pem" \
	"${KEY_DST}"

# === Fix ownership explicitly (numeric UID/GID) ===
chown "${REDIS_UID}:${REDIS_GID}" "${KEY_DST}"

# Prevent reload when service is not fully installed.
# Like when issuing the cert for the first time.
if [ -n "${NO_RELOAD:-}" ]; then
	exit 0
fi


# === Reload TLS material in Valkey ===
redis-cli -a "${password}" -h "${fqdn}" --tls --cert "${CERT_DST}" --key "${KEY_DST}" CONFIG SET tls-cert-file /cert/cert.pem
redis-cli -a "${password}" -h "${fqdn}" --tls --cert "${CERT_DST}" --key "${KEY_DST}"  CONFIG SET tls-key-file /cert/privkey.pem

echo "Redis TLS certificates successfully updated"