services:
  xrootd:
    image: <%= @container_image %>:<%= @container_tag %>
    dns:
      - 89.32.32.32
    hostname: <%= @hostname %>
    volumes:
      - /opt/xrootd/config:/etc/xrootd:ro
      - /dev/log:/dev/log
    command: ["xrootd", "-c", "/etc/xrootd/xrootd.cfg"]
    ports:
      - "<%= @xrootd_port %>:<%= @xrootd_port %>"
    restart: always
  cmsd:
    image: <%= @container_image %>:<%= @container_tag %>
    dns:
      - 89.32.32.32
    hostname: <%= @hostname %>
    volumes:
      - /opt/xrootd/config:/etc/xrootd:ro
      - /dev/log:/dev/log
    command: ["cmsd", "-c", "/etc/xrootd/xrootd.cfg", "-p", "<%= @cms_port %>"]
    ports:
      - "<%= @cms_port %>:<%= @cms_port %>"
