# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  dovecot:
    image: <%= @dovecot_image %>:<%= @dovecot_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/dovecot/config:/etc/dovecot/
      - /opt/dovecot/mail:/var/mail/
    command:
      - /usr/sbin/dovecot
      - -F
    ports:
      - "24:24"
      - "143:143"
      - 993:993
      - 12345:12345
    restart: always

