# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  always-https:
    image: docker.sunet.se/always-https
    dns:
      - 89.32.32.32
    ports:
      - '80:80'
    environment:
      - 'ACME_URL=http://acme-c.sunet.se/'
  dovecot:
    image: <%= @dovecot_image %>:<%= @dovecot_tag %>
    network_mode: host
    dns:
      - 89.32.32.32
    hostname: <%= @hostname %>
    volumes:
      - /opt/dovecot/config/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - /opt/dovecot/config:/etc/dovecot/
      - /opt/dovecot/mail:/var/mail/
      - /etc/dehydrated/certs/:/certs
    command:
      - /usr/sbin/dovecot
      - -F
    ports:
      - "24:24"
      - "143:143"
      - 993:993
      - 4190:4190
      - 12345:12345
      - 12346:12346
    restart: always

