#!/bin/sh -eu
# vim: ai ts=4 sts=4 et sw=4

install -m 644 "${RENEWED_LINEAGE}/fullchain.pem" \
    /opt/discovery/cert/ds.pem
install -m 640 -g 33 \
    "${RENEWED_LINEAGE}/privkey.pem" \
    /opt/discovery/cert/ds.key

docker exec ds nginx -s reload
