
services:
  radicale:
    image: <%= @radicale_image%>:<%= @radicale_tag %> 
    container_name: radicale
    volumes:
      - /etc/dehydrated/certs:/radicale/certs:ro
      - /opt/radicale/conf:/radicale/conf
    environment:
      - TZ=Europe/Stockholm
    restart: unless-stopped
