#!/usr/bin/expect
#
# So since BaaS/TSM cannot be installed without human input we had to create this silly script.
# It needs 2 values as input to run; the TSM nodename and the first-use password from BaaS/Hiera.

# Read input for the TSM bootstrap and set timeout to infinite (any other timeout value breaks flow)
set timeout -1
set nodename [lindex $argv 0]
set password [lindex $argv 1]

if {[llength $argv] == 0} {
  send_user "Usage: scriptname \<nodename\> \<password\>\n"
  exit 1
}

# When this file has been created the installation has (probably) been completed
if {[file exists /etc/adsm/TSM.KDB]} {
  send_user "TSM bootstrap seems completed as /etc/adsm/TSM.KDB already exists. Exiting.\n"
  exit 0
}

spawn "/usr/bin/dsmc"

# Send "username" since TSM doesnt parse the config properly for some reason
expect "Please enter your user" {
  send "$nodename"
  send "\r"
}

# Send "password" since TSM doesnt care about command line supplied options
expect "Please enter password for user" {
  send "$password"
  send "\r"
}

expect "Protect" {
  send "query session\r"
  send "quit\r"
}

exit 0
