#!/usr/bin/env bash

set -e

HOSTNAME=$(hostname -f)
tempfile=$(mktemp)
tempca=$(mktemp)

cat>"${tempfile}"<<EOF
Chrystoki2 = {
   LibUNIX = /usr/safenet/lunaclient/lib/libCryptoki2.so;
   LibUNIX64 = /usr/safenet/lunaclient/lib/libCryptoki2_64.so;
}

Luna = {
  DefaultTimeOut = 500000;
  PEDTimeout1 = 100000;
  PEDTimeout2 = 200000;
  PEDTimeout3 = 20000;
  KeypairGenTimeOut = 2700000;
  CloningCommandTimeOut = 300000;
  CommandTimeOutPedSet = 720000;
}

CardReader = {
  RemoteCommand = 1;
  LunaG5Slots = 0;
  LunaG7Slots = 0;
}

Misc = {
  PE1746Enabled = 0;
  ValidateHost = 0;
   ToolsDir = /usr/safenet/lunaclient/bin;
   PartitionPolicyTemplatePath = /usr/safenet/lunaclient/data/partition_policy_templates;
   ProtectedAuthenticationPathFlagStatus = 0;
   MutexFolder = /usr/safenet/lunaclient/lock;
   PluginModuleDir = /usr/safenet/lunaclient/plugins;
}

Secure Trusted Channel = {
   ClientTokenLib = /usr/safenet/lunaclient/lib/libSoftToken.so;
   SoftTokenDir = /usr/safenet/lunaclient/configData/token;
   ClientIdentitiesDir = /usr/safenet/lunaclient/data/client_identities;
   PartitionIdentitiesDir = /usr/safenet/lunaclient/data/partition_identities;
}

LunaSA Client = {
   ReceiveTimeout = 20000;
   SSLConfigFile = /usr/safenet/lunaclient/bin/openssl.cnf;
   ClientPrivKeyFile = /usr/safenet/lunaclient/cert/client/${HOSTNAME}Key.pem;
   ClientCertFile = /usr/safenet/lunaclient/cert/client/${HOSTNAME}.pem;
   ServerCAFile = /usr/safenet/lunaclient/cert/server/CAFile.pem;
   NetClient = 1;
   TCPKeepAlive = 1;
EOF

N=0

while IFS= read -r -d '' cert
do
#for cert in $(find /usr/safenet/lunaclient/cert/server -name \*Cert.pem); do
   hsm=$(basename "${cert}" Cert.pem)
   NN=$(printf "%02d" "${N}")

cat>>"${tempfile}"<<EOF
   ServerName${NN} = ${hsm};
   ServerPort${NN} = 1792;
   ServerHtl${NN} = 0;
EOF
   ((N=N+1))
   cat "${cert}" >> "${tempca}"
 done < <(find /usr/safenet/lunaclient/cert/server -name \*Cert.pem -print0)
cat>>"${tempfile}"<<EOF
}
EOF

if [ -d /etc/Chrystoki.conf.d ]; then
   cat /etc/Chrystoki.conf.d/*.conf >> /etc/Chrystoki.conf
fi

mv "${tempfile}" /etc/Chrystoki.conf
mv "${tempca}" /usr/safenet/lunaclient/cert/server/CAFile.pem

if [ ! -f "/usr/safenet/lunaclient/cert/client/${HOSTNAME}.pem" ] || [ ! -f "/usr/safenet/lunaclient/cert/client/${HOSTNAME}Key.pem" ]; then
   vtl createCert -n "${HOSTNAME}"
fi
