class sunet::updater($cosmos_automatic_reboot = false, $cron = false) {
   file {'/usr/local/sbin/silent-update-and-upgrade':
      content => "#!/bin/bash\napt-get -qq -y update && env DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confnew' upgrade\n",
      mode    => '0755',
      owner   => 'root',
      group   => 'root'
   }
   if ($cosmos_automatic_reboot) {
      file {'/etc/cosmos-automatic-reboot': 
         content => "# generated by sunet::updater - do not edit or remove by hand"
      }
   } else {
      file {'/etc/cosmos-automatic-reboot': ensure => absent }
   }
   if ($cron) {
      file {'/etc/scriptherder/check/upgrader.ini':
         content => "[check]\n ok      = max_age=25h\n warning = max_age=49h\n"
      }
      cron {'silent-update-and-upgrade':
         command => "scriptherder --mode wrap --syslog --name upgrader -- /usr/local/sbin/silent-update-and-upgrade",
         hour    => '4',
         minute  => '2',
         require => File['/usr/local/sbin/silent-update-and-upgrade']
      }
   }
}
