#!/bin/sh -eu
# vim: ai ts=4 sts=4 et sw=4

mkdir -p /opt/nginx_conf/cert

install -m 644 "${RENEWED_LINEAGE}/fullchain.pem" \
    /opt/nginx_conf/cert/fullchain.pem
install -m 640 -g 33 \
    "${RENEWED_LINEAGE}/privkey.pem" \
    /opt/nginx_conf/cert/privkey.pem

# Prevent reload when service is not fully installed.
# Like when issuing the cert for the first time.
if [ -n "${NO_RELOAD:-}" ]; then
    exit 0
fi

docker exec oidf-ta-nginx-1 nginx -s reload