# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  postfix:
    image: <%= @postfix_image %>:<%= @postfix_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/postfix/config:/config
    command:
      - postfix
      - -v
      - -c
      - /config
      - start-fg
    ports:
      - "25:25"
      - 587:587
    restart: always

