#!/usr/bin/env bash

pref_file="$(mktemp)"

cat > "${pref_file}" <<'EOF'
Package: *
Pin: origin download.docker.com
Pin-Priority: 1000"
EOF

apt-get update
apt-get -o "Dir::Etc::Preferences=${pref_file}" upgrade

rm "${pref_file}"
