#!/bin/sh -eu
# vim: ai ts=4 sts=4 et sw=4

if ! [ -d '/opt/valkey/cert' ]; then
    mkdir -p /opt/valkey/cert
fi

install -m 644 ${RENEWED_LINEAGE}/cert.pem \
    /opt/valkey/cert/cert.pem
# group 101 is freerad inside the container
install -m 640 -g 1000 \
    ${RENEWED_LINEAGE}/privkey.pem \
    /opt/valkey/cert/privkey.pem

# Touch the cert config to allow for the certificate to be re-read.
valkey-connect --custom-command "CONFIG SET tls-cert-file /cert/privkey.pem"
valkey-connect --custom-command "CONFIG SET tls-key-file /cert/privkey.pem"
