# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"

services:
  ldap:
    image: <%= @freeipa_image %>:<%= @freeipa_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw
      - /dev/urandom:/dev/random:ro
      - /opt/freeipa/data:/data
    tmpfs:
      - /run
      - /tmp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    init: false
    cgroup: host
    security_opt:
      - seccomp=unconfined
    environment:
      IPA_SERVER_HOSTNAME: <%= @hostname %>
      IPA_SERVER_INSTALL_OPTS: -U -r <%= @dir_suffix %>
      IPA_SERVER_IP: <%= @ip_address %>
      PASSWORD: "<%= @dir_manager_password %>"
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: <%= @virtual_host %>
      VIRTUAL_PORT: 443
    ports:
      - 53:53
      - 80:80
      - 88:88
      - 123:123
      - 389:389
      - 443:443
      - 464:464
      - 636:636
    restart: always

