# Adapted from https://github.com/michel4j/389ds/blob/master/docker-compose.yml

version: "3.7"
services:
  ldap:
    image: <%= @freeipa_image %>:<%= @freeipa_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw
      - /dev/urandom:/dev/random:ro
      - /opt/freeipa/data:/data:Z
    tmpfs:
      - /run
      - /tmp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    dns:
      - 89.32.32.32
    privileged: true
    init: false
    tty: true
    stdin_open: true
    cgroup: host
    security_opt:
      - seccomp=unconfined
    environment:
      IPA_SERVER_IP: <%= @ip_address %>
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: <%= @hostname %>
      VIRTUAL_PORT: 443
      TZ: "Europe/Stockholm"
    extra_hosts:
      - "<%= @hostname %>:<%= @ip_address %>"
    command:
      - -U
      - --hostname=<%= @hostname %>
      - --domain=<%= @domain %>
      - --realm=<%= @realm %>
      - --admin-password=<%= @password %>
      - --http-pin=<%= @password %>
      - --dirsrv-pin=<%= @password %>
      - --ds-password=<%= @password %>
      - --unattended
    ports:
      - 53:53
      - 80:80
      - 88:88
      - 123:123
      - 389:389
      - 443:443
      - 464:464
      - 636:636
    restart: always
    labels:
      - disable
