#!/usr/bin/env bash
#
# Backup etcd backend for knubbis-fleetlock standalone service.
# Verify the code with shellcheck before commiting changes.
#

if ! etcd_container_id=$(docker inspect --format="{{.Id}}" knubbis-fleetlock_standalone-etcd-1); then
   echo "docker inspect failed"
   exit 1
fi

if [ -z "$etcd_container_id" ]; then
    echo "empty return value from docker inspect"
    exit 1
fi

snapshot_filename="snapshot-$(date +%s).db"

docker exec "$etcd_container_id" etcdctl \
    --cacert=/cert-bootstrap-ca/ca.pem \
    --endpoints=https://etcd:2379 \
    --cert=/cert-bootstrap-client-root/root.pem \
    --key=/cert-bootstrap-client-root/root-key.pem \
    snapshot save /etcd-backup/"$snapshot_filename"

# Cleanup files older than a week
minutes_in_a_week=10080
output=$(find /opt/knubbis-fleetlock/etcd-backup -mmin +$minutes_in_a_week -type f -name 'snapshot-*.db' -delete -ls)
if [ -n "$output" ]; then
    echo "files deleted:"
    echo "$output"
fi
