docker-pull: docker-pull-signer

docker-pull-signer:
	docker pull docker.sunet.se/dc4eu/<%= @pdfsigner_flavor %>:<%= @pdfsigner_version %>

release: docker-pull
	systemctl restart sunet-vc.service

softhsm_clean:
	$(info Deleting and reinitialize the PKCS11 token)
	softhsm2-util --delete-token --token <%= @pkcs11_label %>

softhsm_init:
	$(info init SoftHSM)
	softhsm2-util --init-token --slot 0 --label <%= @pkcs11_label %> --pin <%= @pkcs11_pin %> --so-pin <%= @pkcs11_pin %>

pkcs11-list:
	pkcs11-tool --module <%= @pkcs11_module %> -L --pin <%= @pkcs11_pin %> -T -O -I


	#pkcs11-tool -l -O