
services:
  roundcube:
    image: <%= @roundcube_image%>:<%= @roundcube_tag %>
    container_name: roundcube
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 89.32.32.32
    volumes:
      - '/opt/roundcube/config:/var/roundcube/config'
      - '/opt/roundcube/plugins:/var/www/html/plugins'
      - '/opt/roundcube/certs/:/etc/shibboleth/certs/'
      - '/opt/roundcube/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml'
      - '/opt/roundcube/shib.conf:/etc/apache2/sites-enabled/shib.conf'
    restart: unless-stopped
