version: "3.7"

services:
  always-https:
    image: docker.sunet.se/always-https
    dns:
     - 89.32.32.32
    ports:
     - '80:80'
    environment:
     - 'ACME_URL=http://acme-c.sunet.se/'
  nginx:
    image: docker.io/nginxproxy/nginx-proxy:latest
    container_name: nginx
    dns:
      - 89.32.32.32
    ports:
      - "443:443"
    volumes:
      - /etc/dehydrated/certs/mail.<%= @domain %>/fullchain.pem:/etc/nginx/certs/mail.<%= @domain %>.crt:ro
      - /etc/dehydrated/certs/mail.<%= @domain %>/privkey.pem:/etc/nginx/certs/mail.<%= @domain %>.key:ro
      - /opt/roundcube/nginx/conf:/etc/nginx/conf.d
      - /opt/roundcube/nginx/dhparam:/etc/nginx/dhparam
      - /opt/roundcube/nginx/html:/usr/share/nginx/html
      - /opt/roundcube/nginx/vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    restart: unless-stopped
  web:
    image: <%= @roundcube_image %>:<%= @roundcube_tag %>
    dns:
      - 89.32.32.32
    volumes:
      - /opt/roundcube/config:/var/roundcube/config
  <%- unless @db_ips.empty? -%>
    extra_hosts:
    <%- @db_ips.each do |ip| -%>
      - "sogo-db: <%= ip %>"
    <%- end -%>
  <%- end -%>
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://imap.<%= @domain %>
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp.<%= @domain %>
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=sogo-db
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=<%= @roundcube_password %>
      - VIRTUAL_HOST=mail.<%= @domain %>
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=8000
    ports:
      - 8000:80
    restart: always

