docker-pull: docker-pull-signer

docker-pull-signer:
	docker pull docker.sunet.se/dc4eu/<%= @pdfsigner_flavor %>:<%= @pdfsigner_version %>

release: docker-pull
	systemctl restart sunet-vc.service

clean_softhsm:
	$(info Deleting and reinitialize the PKCS11 token)
	softhsm2-util --delete-token --token <%= @pkcs11_token %>
