version: "3.7"

services:
  always-https:
    image: docker.sunet.se/always-https
    dns:
      - 89.32.32.32
    ports:
      - '80:80'
    environment:
      - 'ACME_URL=http://acme-c.sunet.se/'
  postfix:
    image: <%= @postfix_image %>:<%= @postfix_tag %>
    hostname: <%= @hostname %>
    volumes:
      - /opt/postfix/config:/config
    command:
      - /start.sh
    ports:
      - "25:25"
      - 587:587
    restart: always

