#!/bin/bash

if [ -f /var/run/reboot-required ]; then
	# fleetlock lock
	. /etc/run-cosmos-fleetlock-conf
	sunet-fleetlock --lock-group $fleetlock_group --lock || exit 1
	# drain kube and reboot
	kubectl drain $(hostname) --ignore-daemonsets && systemctl reboot
fi
