#!/bin/sh -eu
# vim: ai ts=4 sts=4 et sw=4

mkdir -p /opt/tunnelbana/keys

install -m 644 "${RENEWED_LINEAGE}/fullchain.pem" \
    /opt/tunnelbana/keys/fullchain.pem
install -m 640 -g 10001 \
    "${RENEWED_LINEAGE}/privkey.pem" \
    /opt/tunnelbana/keys/privkey.pem

# Prevent reload when service is not fully installed.
# Like when issuing the cert for the first time.
if [ -n "${NO_RELOAD:-}" ]; then
    exit 0
fi

pkill -xf '^tunnelbana /app/config/proxy.toml$' -HUP
